import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {ITEMS,BUILDINGS} from '../shared/data.js';
import {emptyBag,add,count,moveSlot} from '../shared/inventory.js';
import {terrain,generateChunk,isWater,placementValid} from '../shared/world.js';
const scratch=path.resolve('..','..','work');fs.mkdirSync(scratch,{recursive:true});const saveDir=fs.mkdtempSync(path.join(scratch,'island-tests-'));process.env.SAVE_DIR=saveDir;
const {createRoom,newPlayer,ensureChunks,spawnEnemy,rooms,saveAll,loadAll}=await import('../server/rooms.js');
const {action,hurtPlayer}=await import('../server/actions.js');
const {tickRoom}=await import('../server/simulation.js');
const {snapshot}=await import('../server/network.js');
function setup(){const r=createRoom(),p=newPlayer('测试旅人'),out=[];p.ws={readyState:1,send:raw=>out.push(JSON.parse(raw))};r.players.set(p.id,p);ensureChunks(r,p);return {r,p,out};}
function stock(p){for(const id of ['wood','branch','stone','fiber','herb','ore'])add(p.bag,id,40);}
test('world generation is deterministic and includes two separated islands and cave walls',()=>{assert.deepEqual(generateChunk(2,3,0,19),generateChunk(2,3,0,19));assert.notEqual(terrain(30,50), 'ocean');assert.notEqual(terrain(87,35),'ocean');assert.equal(terrain(60,40),'ocean');assert.equal(terrain(0,0,1),'wall');assert.equal(terrain(8,24,1),'cave');});
test('inventory conserves items through stacking, splitting and swaps',()=>{const bag=emptyBag(3);assert.equal(add(bag,'wood',120),0);assert.equal(count(bag,'wood'),120);moveSlot(bag,0,2,true);assert.equal(count(bag,'wood'),120);assert.equal(bag[2].n,50);add(bag,'axe');assert.equal(count(bag,'axe'),0);assert.equal(add(bag,'wood',300),123);});
test('server simulation moves by time, not repeated client input, and expires stale input',()=>{const {r,p}=setup();p.input={x:1,y:0};p.inputAt=Date.now();const start=p.x;for(let i=0;i<20;i++)tickRoom(r,.05);assert.ok(Math.abs(p.x-start-2.7)<.01);p.inputAt=0;const x=p.x;tickRoom(r,.05);assert.equal(p.x,x);});
test('gather validates distance and tools, creates shared drops, and auto pickup progresses quest',()=>{const {r,p}=setup();const n={id:'testTree',type:'tree',x:p.x+1,y:p.y,z:0,hp:3,maxHp:3};r.nodes.set(n.id,n);action(r,p,{type:'gather',id:'n0_2_2'});assert.equal(n.hp,3);add(p.bag,'axe');action(r,p,{type:'gather',id:n.id});assert.equal(n.hp,0);assert.ok(r.drops.some(d=>d.item==='wood'));for(const d of r.drops){d.x=p.x;d.y=p.y;}tickRoom(r,.05);assert.equal(count(p.bag,'wood'),4);assert.equal(p.progress.tree,1);});
test('crafting spends materials atomically and requires real nearby stations',()=>{const {r,p}=setup();stock(p);action(r,p,{type:'craft',item:'axe'});assert.equal(count(p.bag,'axe'),1);const before=count(p.bag,'ore');action(r,p,{type:'craft',item:'ingot'});assert.equal(count(p.bag,'ore'),before);r.buildings.push({id:'f',type:'furnace',x:p.x+1,y:p.y,z:0});action(r,p,{type:'craft',item:'ingot'});assert.equal(count(p.bag,'ingot'),1);assert.equal(count(p.bag,'ore'),before-2);});
test('building placement spends cost only on valid placements and chest contents are shared',()=>{const {r,p}=setup();stock(p);const before=count(p.bag,'wood');action(r,p,{type:'build',building:'chest',x:80,y:70});assert.equal(count(p.bag,'wood'),before);action(r,p,{type:'build',building:'chest',x:p.x+1,y:p.y});assert.equal(r.buildings.length,1);const b=r.buildings[0],slot=p.bag.findIndex(s=>s?.id==='wood');action(r,p,{type:'transfer',id:b.id,direction:'deposit',slot});assert.equal(count(b.bag,'wood'),before-6);const q=newPlayer('队友');q.x=p.x;q.y=p.y;r.players.set(q.id,q);action(r,q,{type:'transfer',id:b.id,direction:'withdraw',slot:0});assert.equal(count(q.bag,'wood'),before-6);assert.equal(count(b.bag,'wood'),0);});
test('cave transition changes the replicated world layer and exit restores the surface',()=>{const {r,p}=setup();p.x=18;p.y=22;action(r,p,{type:'interact'});assert.equal(p.z,1);assert.equal(p.progress.cave,1);ensureChunks(r,p);assert.ok(snapshot(r,p).nodes.every(n=>n.z===1));action(r,p,{type:'interact'});assert.equal(p.z,0);});
test('raft carries a driver and passenger and cannot sail onto land',()=>{const {r,p}=setup();const q=newPlayer('同船队友');q.ws={readyState:1,send(){}};q.x=60;q.y=40;p.x=60;p.y=40;r.players.set(q.id,q);const b={id:'boat',type:'raft',x:60,y:40,z:0,driver:p.id,passengers:[q.id]};r.buildings.push(b);p.boat=b.id;q.boat=b.id;p.input={x:1,y:0};p.inputAt=Date.now();tickRoom(r,.05);assert.ok(b.x>60);assert.equal(q.x,b.x);assert.equal(p.x,b.x);assert.ok(isWater(terrain(b.x,b.y)));assert.equal(placementValid(p,'raft',30,51,0,[],BUILDINGS.raft),false);});
test('three enemy types, hit cooldown, death and boss phase transition are authoritative',()=>{const {r,p}=setup();r.enemies.clear();add(p.bag,'spear');p.selected=2;spawnEnemy(r,{id:'target',type:'crab',x:p.x+1,y:p.y,z:0});const e=r.enemies.get('target');action(r,p,{type:'attack'});const hp=e.hp;action(r,p,{type:'attack'});assert.equal(e.hp,hp);spawnEnemy(r,{id:'b',type:'boss',x:p.x+3,y:p.y,z:0,hp:180});tickRoom(r,.05);assert.equal(r.enemies.get('b').phase,3);assert.ok([...r.enemies.values()].some(e=>e.type==='shade'));p.invulnerable=0;hurtPlayer(r,p,200);assert.equal(p.hp,0);r.time+=6;tickRoom(r,.05);assert.equal(p.hp,100);assert.equal(p.x,p.spawn.x);});
test('survival depletion causes actual damage, while supplies recover vitals',()=>{const {r,p}=setup();p.hunger=0;p.thirst=0;tickRoom(r,.05);assert.ok(p.hp<100);action(r,p,{type:'use',item:'berry'});action(r,p,{type:'use',item:'water'});assert.equal(p.hunger,22);assert.equal(p.thirst,35);});
test('interest snapshots exclude distant entities and private session tokens',()=>{const {r,p}=setup();r.nodes.set('distant',{id:'distant',x:90,y:30,z:0,hp:5});const state=snapshot(r,p);assert.ok(!state.nodes.some(n=>n.id==='distant'));assert.ok(!JSON.stringify(state).includes(p.token));assert.ok(state.nodes.length<r.nodes.size);});
test('save and load preserve player inventory, world changes, and reconnect identity',()=>{const {r,p}=setup();add(p.bag,'core',1);r.buildings.push({id:'persisted',type:'campfire',x:30,y:50,z:0,hp:150,maxHp:150});saveAll();rooms.clear();loadAll();const loaded=rooms.get(r.code);assert.equal(loaded.players.get(p.id).token,p.token);assert.equal(count(loaded.players.get(p.id).bag,'core'),1);assert.equal(loaded.buildings[0].id,'persisted');assert.equal(loaded.players.get(p.id).ws,undefined);});
test.after(()=>{if(saveDir.startsWith(scratch+path.sep))fs.rmSync(saveDir,{recursive:true,force:true});});
