import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {groundHeight,cameraDirection} from '../shared/visual-math.js';
test('camera-relative movement preserves speed at every orbit angle',()=>{for(let a=-3.14;a<3.14;a+=.1){for(const [x,y] of [[1,0],[0,-1],[1,1]])assert.ok(Math.abs(Math.hypot(...Object.values(cameraDirection(x,y,a)))-1)<1e-10);}assert.deepEqual(cameraDirection(0,0,1),{x:0,y:0});assert.ok(cameraDirection(0,-1,Math.PI/2).x<-.99);});
test('terrain height is finite and continuous across cell edges',()=>{for(let x=2;x<114;x++)for(let z=2;z<82;z++){assert.ok(Number.isFinite(groundHeight(x,z)));assert.ok(Math.abs(groundHeight(x+.5-1e-6,z)-groundHeight(x+.5+1e-6,z))<.0001);}});
test('all exported models contain valid GLB headers and mesh primitives',()=>{for(const n of ['palm','rock','ruin','shelter','survivor']){const b=fs.readFileSync(new URL('../public/assets/cinematic/'+n+'.glb',import.meta.url));assert.equal(b.toString('utf8',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));assert.ok(j.meshes.every(m=>m.primitives.length));}});
test('browser entrypoint static imports resolve to served files without bare packages',()=>{const root=path.resolve('public'),seen=new Set();function visit(f){if(seen.has(f))return;seen.add(f);assert.ok(fs.existsSync(f),f);const s=fs.readFileSync(f,'utf8').replace(/\/\*[\s\S]*?\*\//g,'').replace(/^\s*\/\/.*$/gm,'');for(const m of s.matchAll(/\bimport\s+(?:[^;]*?\sfrom\s*)?['"]([^'"]+)['"]/g)){const dep=m[1];assert.ok(dep.startsWith('.')||dep.startsWith('/'),'Bare browser import: '+dep);visit(dep.startsWith('/shared/')?path.resolve('.'+dep):dep.startsWith('/')?path.join(root,dep):path.resolve(path.dirname(f),dep));}}visit(path.join(root,'core/game.js'));});

 test('survivor GLB preserves six articulated joints and visible clothing materials',()=>{const b=fs.readFileSync(new URL('../public/assets/cinematic/survivor.glb',import.meta.url));const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));for(const n of ['leg_L','leg_R','arm_L','arm_R','knee_L','knee_R'])assert.ok(j.skins?.some(skin=>skin.joints.some(i=>j.nodes[i].name===n)),n);assert.ok(j.materials.length>=6);});

test('survivor exports skin weights and independent idle/walk clips',()=>{const b=fs.readFileSync(new URL('../public/assets/cinematic/survivor.glb',import.meta.url));const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));assert.ok(j.skins[0].joints.length>=11);for(const name of ['Idle','Walk'])assert.ok(j.animations.find(a=>a.name===name&&a.channels.length));for(const m of j.meshes)for(const p of m.primitives){assert.ok(Number.isInteger(p.attributes.JOINTS_0));assert.ok(Number.isInteger(p.attributes.WEIGHTS_0));}});
