import {ITEMS,RECIPES,BUILDINGS,QUESTS,ENEMIES} from '../shared/data.js';
import {add,count,take,spend,has,emptyBag,moveSlot} from '../shared/inventory.js';
import {distance,terrain,isWater,placementValid,LANDMARKS} from '../shared/world.js';
import {notify,note,nearbyEvent,drop,uid} from './rooms.js';
export function advance(room,p,key,n=1){p.progress[key]=(p.progress[key]||0)+n;while(p.quest<QUESTS.length&&(p.progress[QUESTS[p.quest][1]]||0)>=QUESTS[p.quest][2]){p.quest++;p.xp+=15;notify(p,p.quest===QUESTS.length?'远征完成！取得守卫核心，海岛等待你们继续建设。':`旅途进展：${QUESTS[p.quest][0]}`);}while(p.xp>=p.level*70){p.xp-=p.level*70;p.level++;p.hp=Math.min(100,p.hp+20);notify(p,`成长至 Lv.${p.level} · 生命恢复`);nearbyEvent(room,{kind:'level',x:p.x,y:p.y,z:p.z});}}
function station(room,p,id){return !id||room.buildings.some(b=>b.type===id&&distance(p,b)<4);}
function damageTool(p,id){const i=p.bag.findIndex(s=>s?.id===id&&s.dur);if(i<0)return;p.bag[i].dur--;if(p.bag[i].dur<=0){p.bag[i]=null;notify(p,'工具已损坏，请重新制作。');}}
export function hurtPlayer(room,p,amount){if(p.hp<=0||p.invulnerable>room.time)return;const block=p.input.block&&p.stamina>8;if(block)p.stamina-=8;const armor=p.armor&&count(p.bag,'armor')?5:0;const damage=Math.max(1,amount-armor)*(block?.3:1);p.hp=Math.max(0,p.hp-damage);p.action='hurt';p.actionUntil=room.time+.22;nearbyEvent(room,{kind:'hit',target:p.id,x:p.x,y:p.y,z:p.z,amount:Math.round(damage)});if(p.hp===0){p.action='death';p.actionUntil=room.time+5;p.deadUntil=room.time+5;p.boat=null;for(let i=0;i<p.bag.length;i++){const s=p.bag[i];if(s&&(ITEMS[s.id].stack||99)>1){const n=Math.ceil(s.n/2);drop(room,s.id,n,p.x+(i%3)*.3,p.y,p.z);s.n-=n;if(!s.n)p.bag[i]=null;}}note(room,`${p.name} 倒下了，遗落的物资可由队友拾回。`);}}
export function action(room,p,m){if(p.hp<=0)return;const time=room.time;
 if(m.type==='select'){if(Number.isInteger(m.slot)&&m.slot>=0&&m.slot<9)p.selected=m.slot;return;}
 if(m.type==='hotbar'){if(Number.isInteger(m.slot)&&m.slot>=0&&m.slot<9&&ITEMS[m.item]&&count(p.bag,m.item))p.hotbar[m.slot]=m.item;return;}
 if(m.type==='moveSlot'){moveSlot(p.bag,m.from,m.to,!!m.split);return;}
 if(m.type==='drop'){const s=p.bag[m.slot];if(s&&Number.isInteger(m.slot)){const n=m.split?Math.ceil(s.n/2):s.n;drop(room,s.id,n,p.x+.5,p.y+.5,p.z,s.dur);s.n-=n;if(!s.n)p.bag[m.slot]=null;}return;}
 if(m.type==='use'){const id=m.item||p.hotbar[p.selected],d=ITEMS[id];if(!d||!count(p.bag,id))return;if(id==='armor'){p.armor=!p.armor;return;}if(d.food||d.drink||d.heal){take(p.bag,id,1);p.hunger=Math.min(100,p.hunger+(d.food||0));p.thirst=Math.min(100,p.thirst+(d.drink||0));p.hp=Math.min(100,p.hp+(d.heal||0));nearbyEvent(room,{kind:'heal',x:p.x,y:p.y,z:p.z,amount:d.heal||d.food||d.drink});}return;}
 if(m.type==='craft'){const r=RECIPES[m.item];if(!r)return;if(!station(room,p,r.station))return notify(p,`需要靠近${BUILDINGS[r.station].name}`);if(!has(p.bag,r.cost))return notify(p,'材料不足');const next=structuredClone(p.bag);spend(next,r.cost);if(add(next,m.item,1))return notify(p,'背包已满');p.bag=next;advance(room,p,`craft:${m.item}`);notify(p,`制作完成：${ITEMS[m.item].name}`);return;}
 if(m.type==='build'){const d=BUILDINGS[m.building];if(!d)return;if(!station(room,p,d.station))return notify(p,`需要靠近${BUILDINGS[d.station].name}`);if(!placementValid(p,m.building,m.x,m.y,p.z,room.buildings,d,room.seed))return notify(p,'这里不能建造，请选择附近合适的位置');if(room.buildings.length>=800)return notify(p,'这个世界已达到建筑上限');if(!spend(p.bag,d.cost))return notify(p,'建造材料不足');const b={id:uid(),type:m.building,x:m.x,y:m.y,z:p.z,rotation:Math.floor(Number(m.rotation)||0)%4,hp:d.hp,maxHp:d.hp,owner:p.id};if(b.type==='chest')b.bag=emptyBag(16);if(b.type==='raft'){b.driver=null;b.passengers=[];}room.buildings.push(b);p.action='build';p.actionUntil=time+.5;advance(room,p,`build:${b.type}`);nearbyEvent(room,{kind:'build',x:b.x,y:b.y,z:b.z});return;}
 if(m.type==='demolish'||m.type==='repair'){const b=room.buildings.find(b=>b.id===m.id);if(!b||distance(p,b)>3||b.type==='raft'&&(b.driver||b.passengers?.length))return;if(m.type==='repair'){if(spend(p.bag,{wood:2}))b.hp=b.maxHp;}else{if(b.bag?.some(Boolean))return notify(p,'请先清空箱子');room.buildings=room.buildings.filter(v=>v!==b);for(const [id,n]of Object.entries(BUILDINGS[b.type].cost))drop(room,id,Math.max(1,Math.floor(n/2)),b.x,b.y,b.z);}return;}
 if(m.type==='transfer'){const b=room.buildings.find(b=>b.id===m.id&&b.type==='chest');if(!b||distance(p,b)>3||!Number.isInteger(m.slot))return;const src=m.direction==='deposit'?p.bag:b.bag,dst=m.direction==='deposit'?b.bag:p.bag,s=src[m.slot];if(!s)return;const requested=m.split?Math.ceil(s.n/2):s.n,left=add(dst,s.id,requested,s.dur);s.n-=requested-left;if(!s.n)src[m.slot]=null;return;}
 if(m.type==='dodge'){if(p.stamina<22||p.boat||p.dodgeCooldown>time)return;const n=Math.hypot(p.input.x||0,p.input.y||0);p.dodgeX=n?(p.input.x||0)/n:Math.cos(p.facing||0);p.dodgeY=n?(p.input.y||0)/n:Math.sin(p.facing||0);p.stamina-=22;p.invulnerable=time+.3;p.dodgeUntil=time+.3;p.dodgeCooldown=time+.8;p.action='dodge';p.actionUntil=time+.3;return;}
 if(m.type==='interact'){
  if(p.boat){const b=room.buildings.find(b=>b.id===p.boat);let land;for(let a=0;a<16;a++){const x=p.x+Math.cos(a*Math.PI/8)*2,y=p.y+Math.sin(a*Math.PI/8)*2;if(!isWater(terrain(x,y,p.z,room.seed))&&terrain(x,y,p.z,room.seed)!=='wall'){land={x,y};break;}}if(!land)return notify(p,'靠近岸边再下船');if(b){if(b.driver===p.id)b.driver=null;b.passengers=b.passengers.filter(v=>v!==p.id);}p.boat=null;Object.assign(p,land);return;}
  const l=LANDMARKS.find(l=>distance(p,l)<2.6&&['cave','exit','spring','relic'].includes(l.id));if(l){if(l.id==='cave'){p.z=1;p.x=8;p.y=24;advance(room,p,'cave');notify(p,'进入幽光洞窟 · 制作火把可扩大视野');}else if(l.id==='exit'){p.z=0;p.x=18;p.y=24;}else if(l.id==='spring'){add(p.bag,'water',3);notify(p,'灌满了 3 份淡水');}else if(!p.progress.relic){add(p.bag,'shard',3);p.progress.relic=1;notify(p,'发现古代碎片，东岛的守卫正在苏醒。');}return;}
  const b=room.buildings.filter(b=>distance(p,b)<2.6).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(b){if(b.type==='raft'){if(!b.driver)b.driver=p.id;else if(b.passengers.length<7)b.passengers.push(p.id);else return;p.boat=b.id;return;}if(b.type==='door'){b.open=!b.open;return;}if(b.type==='well'){add(p.bag,'water',3);return;}if(b.type==='bed'){p.spawn={x:b.x,y:b.y,z:b.z};p.hp=Math.min(100,p.hp+20);p.sanity=100;p.hunger=Math.max(0,p.hunger-8);p.thirst=Math.max(0,p.thirst-8);notify(p,'休息完成，复活点已设置');return;}if(b.type==='chest')return notify(p,'打开背包，可存取附近共享箱子');}
 }
 if(m.type==='gather'||m.type==='interact'){
  if(p.cooldown>time)return;const d=room.drops.filter(d=>distance(p,d)<2).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(d){const left=add(p.bag,d.item,d.n,d.dur),picked=d.n-left;d.n=left;if(!left)room.drops=room.drops.filter(v=>v!==d);if(picked){advance(room,p,d.item,picked);nearbyEvent(room,{kind:'loot',x:d.x,y:d.y,z:d.z,item:d.item,amount:picked});}return;}
  const n=m.id?room.nodes.get(m.id):[...room.nodes.values()].filter(n=>n.hp>0&&distance(p,n)<2.4).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(!n||n.hp<=0||distance(p,n)>2.6)return;
  const equipped=p.hotbar[p.selected],tool=count(p.bag,equipped)?ITEMS[equipped]:null,hard=['rock','ore','crystal'].includes(n.type),tree=['tree','palm'].includes(n.type);if(['ore','crystal'].includes(n.type)&&tool?.tool!=='stone')return notify(p,'这种矿物需要装备石镐');const power=(hard&&tool?.tool==='stone'||tree&&tool?.tool==='wood')?tool.power:1;
  p.facing=Math.atan2(n.y-p.y,n.x-p.x);p.cooldown=time+.45;p.action=hard?'mine':tree?'chop':'gather';p.actionUntil=time+.4;p.stamina=Math.max(0,p.stamina-1);n.hp-=power;room.nodeVersion=(room.nodeVersion||0)+1;if(tool?.tool)damageTool(p,equipped);nearbyEvent(room,{kind:'gather',target:n.id,x:n.x,y:n.y,z:n.z,amount:power,material:hard?'stone':'wood',fell:n.hp<=0});
  if(n.hp<=0){n.respawn=time+300;const loot=tree?[['wood',4],['branch',2],['fiber',1]]:n.type==='rock'?[['stone',4]]:n.type==='ore'?[['ore',3],['stone',1]]:n.type==='crystal'?[['crystal',2]]:n.type==='mushroom'?[['herb',2]]:[[n.type, n.type==='berry'?3:2]];for(const [id,qty]of loot)drop(room,id,qty,n.x+Math.random()*.6,n.y+Math.random()*.6,n.z);if(tree)advance(room,p,'tree');p.xp+=2;}return;
 }
 if(m.type==='attack'){
  if(p.cooldown>time||p.stamina<5)return;const equipped=p.hotbar[p.selected],weapon=count(p.bag,equipped)?ITEMS[equipped]:null;const charged=!!m.charged&&p.stamina>=20;p.stamina-=charged?20:5;p.cooldown=time+(charged?.9:.48);p.action='attack';p.actionUntil=time+.35;
  const enemy=[...room.enemies.values()].filter(e=>e.hp>0&&distance(p,e)<(weapon?.reach||1.7)+(e.type==='boss'?.8:0)).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(!enemy)return;p.facing=Math.atan2(enemy.y-p.y,enemy.x-p.x);const crit=Math.random()<.12,damage=Math.round((weapon?.damage||6)*(charged?1.8:1)*(crit?1.5:1));enemy.hp=Math.max(0,enemy.hp-damage);enemy.target=p.id;enemy.stunUntil=time+.12;enemy.hitAt=time;nearbyEvent(room,{kind:'hit',target:enemy.id,x:enemy.x,y:enemy.y,z:enemy.z,amount:damage,crit});if(weapon?.damage)damageTool(p,equipped);
  if(enemy.hp<=0){p.xp+=ENEMIES[enemy.type].xp;drop(room,enemy.type==='boss'?'core':enemy.type==='shade'?'crystal':'meat',enemy.type==='boss'?1:2,enemy.x,enemy.y,enemy.z);enemy.respawn=time+180;if(enemy.type==='boss'){room.bossDead=true;for(const other of room.players.values())if(distance(other,enemy)<25){advance(room,other,'boss');notify(other,'潮汐守卫已倒下！拾取核心，远征胜利。');}note(room,'潮汐守卫已被远征队击败。');}advance(room,p,'kill');}return;
 }
}
