export const ITEMS={
 wood:{name:'木材',icon:'🪵'},branch:{name:'树枝',icon:'🌿'},stone:{name:'石块',icon:'🪨'},fiber:{name:'纤维',icon:'🌾'},berry:{name:'浆果',icon:'🍒',food:22},water:{name:'淡水',icon:'💧',drink:35},ore:{name:'铁矿',icon:'⛏'},crystal:{name:'幽光水晶',icon:'💎'},shard:{name:'古代碎片',icon:'🔹'},core:{name:'守卫核心',icon:'🔮'},meat:{name:'生肉',icon:'🥩',food:12},ration:{name:'烤肉餐',icon:'🍖',food:55,heal:10},herb:{name:'药草',icon:'🍃'},ingot:{name:'铁锭',icon:'▰'},
 axe:{name:'石斧',icon:'🪓',tool:'wood',power:3,durability:100,stack:1},pickaxe:{name:'石镐',icon:'⛏',tool:'stone',power:3,durability:100,stack:1},spear:{name:'木矛',icon:'⚔',damage:18,reach:2.4,durability:100,stack:1},sword:{name:'铁剑',icon:'🗡',damage:32,reach:2.1,durability:160,stack:1},torch:{name:'火把',icon:'🔥',stack:1},armor:{name:'皮革衣',icon:'🦺',armor:5,stack:1},bandage:{name:'绷带',icon:'✚',heal:35}
};
export const RECIPES={
 axe:{cost:{branch:3,stone:2},desc:'砍树效率 ×3。'},pickaxe:{cost:{wood:3,stone:3},desc:'开采矿石和洞穴水晶。'},spear:{cost:{wood:4,fiber:2},desc:'安全距离攻击，右键格挡。'},torch:{cost:{wood:2,fiber:2},desc:'照亮洞穴，放在背包即可生效。'},bandage:{cost:{fiber:3,herb:1},desc:'恢复 35 生命。'},ration:{cost:{meat:1,berry:2},station:'campfire',desc:'烹饪补给，恢复饱腹和生命。'},armor:{cost:{fiber:8,wood:3},station:'workbench',desc:'穿上后抵挡 5 点伤害。'},ingot:{cost:{ore:2,wood:2},station:'furnace',desc:'熔炼后用于高级装备。'},sword:{cost:{ingot:3,wood:3},station:'workbench',desc:'铁器时代的可靠武器。'}
};
export const BUILDINGS={
 campfire:{name:'篝火',icon:'🔥',cost:{wood:5,stone:3},desc:'温暖、照明与烹饪',radius:.65,hp:150},workbench:{name:'工作台',icon:'🛠',cost:{wood:8,stone:4},desc:'解锁护甲与高级制作',radius:.8,hp:200},foundation:{name:'木地基',icon:'▱',cost:{wood:4},desc:'建立自己的营地',radius:.48,hp:200},wall:{name:'木墙',icon:'▥',cost:{wood:3},desc:'阻挡野兽与敌人',radius:.42,hp:200,solid:true},door:{name:'木门',icon:'▣',cost:{wood:4,fiber:1},desc:'按 E 开关营地入口',radius:.42,hp:180,solid:true},roof:{name:'棚顶',icon:'⌂',cost:{wood:5,fiber:3},desc:'避雨，改善体温',radius:.5,hp:150},chest:{name:'共享箱子',icon:'▣',cost:{wood:6},desc:'全队共享 16 格物资',radius:.65,hp:180},furnace:{name:'熔炉',icon:'♨',cost:{stone:10,ore:2},station:'workbench',desc:'将铁矿熔炼成铁锭',radius:.8,hp:300},bed:{name:'睡袋',icon:'▰',cost:{fiber:6,wood:2},desc:'休息回血，设置复活点',radius:.65,hp:100},well:{name:'水井',icon:'💧',cost:{stone:8,wood:4},desc:'营地的稳定淡水来源',radius:.65,hp:220},raft:{name:'木筏',icon:'⛵',cost:{wood:12,fiber:6},station:'workbench',desc:'在岸边水面建造，E 登船',radius:1.15,hp:300,water:true}
};
export const HOTBAR=['axe','pickaxe','spear','berry','water','bandage','torch',null,null];
export const QUESTS=[['拾取海滩上的树枝','branch',3],['拾取石块，制作石斧','craft:axe',1],['装备石斧，砍倒一棵树','tree',1],['建造第一堆篝火','build:campfire',1],['制作工作台','build:workbench',1],['制作木矛，准备探索','craft:spear',1],['进入幽光洞窟','cave',1],['建造木筏，驶向东岛','build:raft',1],['发现沉眠遗迹','island',1],['击败潮汐守卫，取得核心','boss',1]];
export const ENEMIES={crab:{name:'岩滩蟹',hp:34,damage:6,speed:1.3,xp:10},boar:{name:'野猪',hp:65,damage:10,speed:2.1,xp:20},shade:{name:'幽光蛛',hp:48,damage:8,speed:2.3,xp:25},boss:{name:'潮汐守卫',hp:700,damage:22,speed:1.15,xp:180}};
export const WEATHER=['晴朗','薄雾','小雨','雷暴'];
